"use client";
import { useState } from "react";
import { processSteps } from "@/data/process";
export function ProcessSection(){
 const [active,setActive]=useState(0);
 return <section id="proceso" className="section-shell bg-[#050816]"><div className="v-container"><p className="tech-label text-cyan-300">04 / Proceso</p><h2 className="display mt-6 max-w-6xl text-[clamp(3.2rem,7vw,7rem)]">De una idea<br/>a un sistema real.</h2><div className="mt-16 grid gap-8 lg:grid-cols-[.8fr_1.2fr]">
  <div>{processSteps.map((step,index)=><button key={step.number} onClick={()=>setActive(index)} onMouseEnter={()=>setActive(index)} className={`flex w-full gap-5 border-t py-5 text-left transition ${active===index?"border-cyan-300 text-white":"border-white/10 text-white/35"}`}><span className="tech-label mt-1">{step.number}</span><span><strong className="display block text-3xl">{step.title}</strong><span className="mt-2 block max-w-md text-sm leading-6">{step.text}</span></span></button>)}</div>
  <div className="sticky top-28 h-[min(70svh,620px)] overflow-hidden rounded-[2rem] border border-white/10 bg-[#080d1a] p-5"><div className="flex items-center gap-2 border-b border-white/10 pb-4"><i className="size-2 rounded-full bg-cyan-300"/><i className="size-2 rounded-full bg-white/20"/><i className="size-2 rounded-full bg-white/20"/><span className="tech-label ml-auto">Build / phase 0{active+1}</span></div><div className="grid-bg relative mt-5 h-[calc(100%-3.5rem)] overflow-hidden rounded-xl border border-white/10"><div className="absolute left-[8%] top-[10%] h-5 w-1/2 rounded bg-white/10"/><div className="absolute left-[8%] top-[20%] h-16 w-4/5 rounded border border-cyan-300/20 bg-cyan-300/[.04]"/>{active>1&&<><div className="absolute left-[8%] top-[43%] h-28 w-[38%] rounded-xl bg-purple-500/10"/><div className="absolute right-[8%] top-[43%] h-28 w-[38%] rounded-xl bg-blue-500/10"/></>}{active>2&&<div className="absolute bottom-[12%] left-[8%] right-[8%] h-20 rounded-xl border border-cyan-300/30 bg-cyan-300/[.06] p-4 font-mono text-[10px] text-cyan-200">&lt;Experience status=&quot;ready&quot; /&gt;</div>}<svg className="absolute inset-0 size-full"><path d="M40 80 C180 30 260 260 520 160" fill="none" stroke="#00e5ff" strokeDasharray="6 9" opacity=".4"/></svg></div></div>
 </div></div></section>;
}
