import type { Metadata } from "next";
import Link from "next/link";
import { Check, Minus, ArrowUpRight } from "lucide-react";
import { InteriorPage } from "@/components/layout/interior-page";
import { PageHero } from "@/components/ui/page-hero";
import { QuoteStrip } from "@/components/ui/quote-strip";
import { pricingTiers, serviceCatalog } from "@/data/offers";

export const metadata: Metadata = { title: "Precios y paquetes | Vexora Labs", description: "Paquetes Starter, Core y Scale con alcance transparente y precios desde en MXN." };

export default function PricingPage(){
 return <InteriorPage><PageHero index="02" eyebrow="Precios" title={<>Claridad antes<br/>de construir.</>} description="Paquetes orientativos para decidir rápido. El precio final se confirma después de entender objetivo, alcance, contenido, integraciones y plazo."/>
  <section className="section-shell bg-[#050816]"><div className="v-container"><div className="grid gap-4 lg:grid-cols-3">{pricingTiers.map((tier,index)=><article key={tier.name} className={"relative flex min-h-[620px] flex-col overflow-hidden rounded-[2rem] border p-7 md:p-9 "+(tier.featured?"border-cyan-300/45 bg-cyan-300/[.075] shadow-[0_0_100px_rgba(0,229,255,.08)]":"border-white/10 bg-white/[.035]")}><div className="flex justify-between"><span className="tech-label text-cyan-300">0{index+1} / {tier.badge}</span>{tier.featured&&<span className="rounded-full bg-cyan-300 px-3 py-1 text-[9px] font-bold uppercase tracking-wider text-slate-950">Recomendado</span>}</div><h2 className="display mt-12 text-5xl">{tier.name}</h2><p className="mt-5 min-h-14 text-sm leading-6 text-white/55">{tier.description}</p><div className="mt-8"><span className="tech-label">Desde</span><strong className="display mt-2 block text-6xl text-white">{tier.price}</strong><span className="text-xs text-white/35">MXN · pago único</span></div><ul className="mt-9 space-y-3">{tier.included.map(item=><li key={item} className="flex gap-3 text-sm text-white/70"><Check size={15} className="mt-0.5 shrink-0 text-cyan-300"/>{item}</li>)}</ul><ul className="mt-6 space-y-2 border-t border-white/10 pt-5">{tier.excluded.map(item=><li key={item} className="flex gap-3 text-xs text-white/35"><Minus size={14} className="shrink-0"/>{item}</li>)}</ul><Link href="/contacto" className={"mt-auto inline-flex min-h-12 items-center justify-center gap-2 rounded-full text-xs font-bold uppercase tracking-wider "+(tier.featured?"bg-cyan-300 text-slate-950":"border border-white/15 text-white")}>Cotizar {tier.name} <ArrowUpRight size={15}/></Link></article>)}</div>
   <div className="mt-16 grid gap-4 rounded-[2rem] border border-white/10 bg-[#080d1a] p-7 md:grid-cols-[1fr_auto] md:items-center md:p-10"><div><p className="tech-label text-purple-300">Continuidad opcional</p><h2 className="display mt-4 text-4xl md:text-6xl">Soporte desde $1,500/mes.</h2><p className="mt-4 max-w-2xl text-sm leading-7 text-white/50">Mantenimiento, ajustes menores, monitoreo básico y prioridad de respuesta en días hábiles.</p></div><Link href="/contacto" className="inline-flex min-h-12 items-center rounded-full bg-white px-6 text-xs font-bold uppercase tracking-wider text-slate-950">Solicitar soporte</Link></div>
  </div></section>
  <section className="section-shell bg-[#030712]"><div className="v-container"><p className="tech-label text-cyan-300">Comparación rápida</p><h2 className="display mt-5 text-[clamp(3rem,6vw,6rem)]">Servicios individuales.</h2><div className="mt-10 overflow-hidden rounded-2xl border border-white/10"><div className="hidden grid-cols-[1.4fr_.7fr_.7fr] bg-white/[.06] px-6 py-4 text-[10px] uppercase tracking-wider text-white/40 md:grid"><span>Servicio</span><span>Desde</span><span>Tiempo</span></div>{serviceCatalog.slice(0,8).map(service=><div key={service.slug} className="grid gap-3 border-t border-white/10 px-5 py-5 md:grid-cols-[1.4fr_.7fr_.7fr] md:items-center md:px-6"><strong className="text-sm">{service.title}</strong><span className="text-sm text-cyan-200">{service.price} MXN</span><span className="text-xs text-white/45">{service.time}</span></div>)}</div><p className="mt-5 text-xs leading-6 text-white/35">Los precios son orientativos y pueden variar por alcance, urgencia, número de pantallas, contenido, integraciones y personalización.</p></div></section><QuoteStrip title="Empieza profesional. Escala cuando tenga sentido."/></InteriorPage>;
}
