"use client";
import { useEffect, useRef } from "react";
import { useReducedMotion } from "@/hooks/use-reduced-motion";
interface Props { words?: string[]; colors?: string[]; interval?: number; className?: string; interactive?: boolean; }
export function ParticleTextEffect({words=["DISEÑAMOS","CONSTRUIMOS","CONECTAMOS"],colors=["#fff","#00e5ff","#8b5cf6"],interval=1700,className="",interactive=true}:Props){
 const canvas=useRef<HTMLCanvasElement>(null);const reduced=useReducedMotion();
 useEffect(()=>{const el=canvas.current;if(!el||reduced)return;const ctx=el.getContext("2d");if(!ctx)return;let frame=0,index=0,last=0;let particles:{x:number;y:number;tx:number;ty:number;c:string}[]=[];let visible=true;const pointer={x:-999,y:-999};
 const build=()=>{const rect=el.getBoundingClientRect();if(rect.width<1||rect.height<1)return;const dpr=Math.min(devicePixelRatio,1.5);el.width=rect.width*dpr;el.height=rect.height*dpr;ctx.setTransform(dpr,0,0,dpr,0,0);ctx.clearRect(0,0,rect.width,rect.height);ctx.font=`600 ${Math.min(rect.width*.12,120)}px sans-serif`;ctx.textAlign="center";ctx.textBaseline="middle";ctx.fillText(words[index],rect.width/2,rect.height/2);const data=ctx.getImageData(0,0,el.width,el.height).data;const next=[];for(let y=0;y<el.height;y+=8*dpr)for(let x=0;x<el.width;x+=8*dpr)if(data[(Math.floor(y)*el.width+Math.floor(x))*4+3]>80)next.push({x:Math.random()*rect.width,y:Math.random()*rect.height,tx:x/dpr,ty:y/dpr,c:colors[index%colors.length]});particles=next;ctx.clearRect(0,0,rect.width,rect.height);};
 const draw=(time:number)=>{const rect=el.getBoundingClientRect();if(time-last>interval){index=(index+1)%words.length;last=time;build();}ctx.clearRect(0,0,rect.width,rect.height);for(const p of particles){p.x+=(p.tx-p.x)*.08;p.y+=(p.ty-p.y)*.08;if(interactive){const dx=p.x-pointer.x,dy=p.y-pointer.y,d=Math.hypot(dx,dy);if(d<70){p.x+=dx/d*2;p.y+=dy/d*2;}}ctx.fillStyle=p.c;ctx.fillRect(p.x,p.y,1.6,1.6);}if(visible)frame=requestAnimationFrame(draw);};
 const resize=new ResizeObserver(build);const observer=new IntersectionObserver(([entry])=>{visible=entry.isIntersecting;if(visible)frame=requestAnimationFrame(draw);else cancelAnimationFrame(frame);});const move=(e:PointerEvent)=>{const r=el.getBoundingClientRect();pointer.x=e.clientX-r.left;pointer.y=e.clientY-r.top;};resize.observe(el);observer.observe(el);el.addEventListener("pointermove",move);build();frame=requestAnimationFrame(draw);return()=>{cancelAnimationFrame(frame);resize.disconnect();observer.disconnect();el.removeEventListener("pointermove",move);};},[words,colors,interval,interactive,reduced]);
 return <div className={className}><span className="sr-only">{words.join(" ")}</span>{reduced?<p className="display text-center text-[clamp(3rem,10vw,8rem)]">{words.join(" ")}</p>:<canvas ref={canvas} aria-hidden className="h-full w-full"/>}</div>;
}
